DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS MOVIES;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS ORDERLINE;

CREATE TABLE USERS (
  USER_ID INT    PRIMARY KEY NOT NULL,
  USER_NAME TEXT     ,
  PASSWORD TEXT,
  USER_EMAIL TEXT            NOT NULL,
  USER_TYPE INT NOT NULL DEFAULT 0,
  FIRST_NAME TEXT,
  LAST_NAME TEXT,
  PAYMENT_INFO TEXT,
  DISCOUNT_RATE FLOAT,
  CREATION_DATE DATE
);

CREATE TABLE MOVIES (
  MOVIE_ID INT    PRIMARY KEY NOT NULL,
  MOVIE_NAME TEXT       NOT NULL,
  MOVIE_GENRE TEXT            NOT NULL,
  MOVIE_YEAR INT            NOT NULL
);

CREATE TABLE ORDERS (
  ORDER_ID INT PRIMARY KEY NOT NULL,
  USER_ID INT NOT NULL,
  CREATION_DATE DATE NOT NULL,
  ORDER_NO TEXT NOT NULL,
  IS_LIMITED BOOLEAN NOT NULL,
  FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE ORDERLINE (
  ORDERLINE_ID INT PRIMARY KEY NOT NULL,
  ORDER_ID INT NOT NULL,
  MOVIE_ID INT NOT NULL,
  PURCHASE_PRICE FLOAT NOT NULL,
  DISCOUNT_PERCENT INT,
  NO_DAYS INT NOT NULL,
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
  FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(MOVIE_ID)
)