INSERT INTO MOVIES (MOVIE_ID, MOVIE_NAME, MOVIE_GENRE, MOVIE_YEAR) VALUES (1, 'Godfather', 'Crime', 1972);
INSERT INTO MOVIES (MOVIE_ID, MOVIE_NAME, MOVIE_GENRE, MOVIE_YEAR) VALUES (2, 'Inception', 'Drama', 2013);
INSERT INTO MOVIES (MOVIE_ID, MOVIE_NAME, MOVIE_GENRE, MOVIE_YEAR) VALUES (3, 'Terminator', 'SF', 2013);
INSERT INTO MOVIES (MOVIE_ID, MOVIE_NAME, MOVIE_GENRE, MOVIE_YEAR) VALUES (4, 'The Notebook', 'Drama', 2010);

INSERT INTO USERS (USER_ID, USER_NAME, PASSWORD, USER_EMAIL, USER_TYPE, FIRST_NAME, LAST_NAME, PAYMENT_INFO, DISCOUNT_RATE, CREATION_DATE) VALUES (1, 'dan', 'password', 'dan@dan.com', 0, 'Dan', 'Johnson', null, null, '1436302800000');
INSERT INTO USERS (USER_ID, USER_NAME, PASSWORD, USER_EMAIL, USER_TYPE, FIRST_NAME, LAST_NAME, PAYMENT_INFO, DISCOUNT_RATE, CREATION_DATE) VALUES (2, 'joe ', 'password', 'joe@krk.co.uk', 1, 'Joe', 'Snow', null, 10, '1433624400000');
INSERT INTO USERS (USER_ID, USER_NAME, PASSWORD, USER_EMAIL, USER_TYPE, FIRST_NAME, LAST_NAME, PAYMENT_INFO, DISCOUNT_RATE, CREATION_DATE) VALUES (3, 'jim ', 'password', 'jim@tgt.us', 1, 'Jim', null, 'Visa 122312321', null, '1436302800000');
INSERT INTO USERS (USER_ID, USER_NAME, PASSWORD, USER_EMAIL, USER_TYPE, FIRST_NAME, LAST_NAME, PAYMENT_INFO, DISCOUNT_RATE, CREATION_DATE) VALUES (4, 'old', 'password', 'old', 0, null, null, null, null, '1433192400000');

INSERT INTO ORDERS (ORDER_ID, USER_ID, CREATION_DATE, ORDER_NO, IS_LIMITED) VALUES (2, 12, '1436475600000', 'dasda', 1);
